### ISSUE TITLE
propose to add a new folder called ref_apps

### ISSUE THREAD

**Issue by xuechendi** [intel/llm-on-ray#137]
Purpose:
- provides more examples and not add unnecessary codes to webui.
- easily add/remove, seperate ref apps case by case
- as temporary store, upstream to Intel's genAI example repo in future.

**Comment by xuechendi** [comment]
@carsonwang , propose to add a new folder for rec apps

**Comment by xwu99** [comment]
@xuechendi could we call them "demo" rather than ref_apps ?

**Comment by xwu99** [comment]
Already added llm-on-ray/application, but I think it's better to names `applications` and move current one into a subdir.
