### ISSUE TITLE
Issue with running Lama70 model: (ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1')

### ISSUE THREAD

**Issue by rajeshkumarramamurthy** [intel/llm-on-ray#168]
following the instructions from the page:https://github.com/intel/llm-on-ray/blob/main/docs/setup.md

docker run -it --runtime=habana --name="lama" -v $volume:/data -e OMPI_MCA_btl_vader_single_copy_mechanism=none--cap-add=sys_nice --ipc=host llm-on-ray:habana

getting below error with 
python inference/serve.py --config_file inference/models/hpu/llama-2-70b-chat-hf-hpu.yaml --keep_serve_terminal

Enclosed the error message.

root@4b05625be541:~/llm-on-ray/llm_on_ray# python inference/serve.py --config_file inference/models/hpu/llama-2-70b-chat-hf-hpu.yaml --keep_serve_terminal
2024-03-30 05:05:05,006 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 172.17.0.2:6379...
2024-03-30 05:05:05,011 INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at 172.17.0.2:8265
reading from config file, inference/models/hpu/llama-2-70b-chat-hf-hpu.yaml
[WARNING 2024-03-30 05:05:05,031] api.py: 372  DeprecationWarning: `route_prefix` in `@serve.deployment` has been deprecated. To specify a route prefix for an application, pass it into `serve.run` instead.
/usr/local/lib/python3.10/dist-packages/ray/serve/api.py:492: UserWarning: Specifying host and port in `serve.run` is deprecated and will be removed in a future version. To specify custom HTTP options, use `serve.start`.
  warnings.warn(
[INFO 2024-03-30 05:05:05,062] api.py: 281  Connecting to existing Serve app in namespace "serve". New http options will not be applied.
(ServeController pid=9007) INFO 2024-03-30 05:05:05,151 controller 9007 deployment_state.py:1547 - Deploying new version of deployment PredictorDeployment in application 'router'. Setting initial target number of replicas to 1.
(ServeController pid=9007) INFO 2024-03-30 05:05:05,153 controller 9007 deployment_state.py:1547 - Deploying new version of deployment Router in application 'router'. Setting initial target number of replicas to 1.
(ServeController pid=9007) INFO 2024-03-30 05:05:05,257 controller 9007 deployment_state.py:1710 - Stopping 1 replicas of deployment 'PredictorDeployment' in application 'router' with outdated versions.
(ServeController pid=9007) INFO 2024-03-30 05:05:05,259 controller 9007 deployment_state.py:1710 - Stopping 1 replicas of deployment 'Router' in application 'router' with outdated versions.
(ServeController pid=9007) INFO 2024-03-30 05:05:07,611 controller 9007 deployment_state.py:2185 - Replica router#PredictorDeployment#joTskR is stopped.
(ServeController pid=9007) INFO 2024-03-30 05:05:07,611 controller 9007 deployment_state.py:1831 - Adding 1 replica to deployment PredictorDeployment in application 'router'.
(ServeController pid=9007) INFO 2024-03-30 05:05:07,940 controller 9007 deployment_state.py:2185 - Replica router#Router#RZTxfs is stopped.
(ServeController pid=9007) INFO 2024-03-30 05:05:07,940 controller 9007 deployment_state.py:1831 - Adding 1 replica to deployment Router in application 'router'.
(ServeReplica:router:PredictorDeployment pid=17618) [WARNING|utils.py:198] 2024-03-30 05:05:13,268 >> optimum-habana v1.10.4 has been validated for SynapseAI v1.14.0 but the driver version is v1.12.0, this could lead to undefined behavior!
(ServeReplica:router:PredictorDeployment pid=17618) /usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py:711: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
(ServeReplica:router:PredictorDeployment pid=17618)   warnings.warn(
(pid=17870) [WARNING|utils.py:198] 2024-03-30 05:05:19,772 >> optimum-habana v1.10.4 has been validated for SynapseAI v1.14.0 but the driver version is v1.12.0, this could lead to undefined behavior!
(pid=17875) [WARNING|utils.py:198] 2024-03-30 05:05:19,916 >> optimum-habana v1.10.4 has been validated for SynapseAI v1.14.0 but the driver version is v1.12.0, this could lead to undefined behavior!
(HPUDeepSpeedWorker pid=17870) /usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/__init__.py:158: UserWarning: torch.hpu.setDeterministic is deprecated and will be removed in next release. Please use torch.use_deterministic_algorithms instead.
(HPUDeepSpeedWorker pid=17870)   warnings.warn(
(HPUDeepSpeedWorker pid=17869) [2024-03-30 05:05:21,734] [INFO] [real_accelerator.py:178:get_accelerator] Setting ds_accelerator to hpu (override)
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17871, ip=172.17.0.2, actor_id=7257ee545c30865dfc0573d001000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7ee9b2d146d0>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17872, ip=172.17.0.2, actor_id=626076e1dd5423ca50d733f001000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7f4a826c8760>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17876, ip=172.17.0.2, actor_id=a10c5d3a18150fbaded9a2c201000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7f263de84670>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17869, ip=172.17.0.2, actor_id=c40e313d02c9bf2b46f0b7b101000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7f07e39c8760>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17875, ip=172.17.0.2, actor_id=9e317dc19869e2c65e4a803101000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7f25f39f0610>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17873, ip=172.17.0.2, actor_id=087a4563591269649bf93f9c01000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7f0919c80700>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment
Loading 0 checkpoint shards: 0it [00:00, ?it/s]
(HPUDeepSpeedWorker pid=17869) [2024-03-30 05:05:24,019] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.12.4+hpu.synapse.v1.14.0, git-hash=fad45b2, git-branch=1.14.0
(HPUDeepSpeedWorker pid=17869) [2024-03-30 05:05:24,021] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
(HPUDeepSpeedWorker pid=17869) [2024-03-30 05:05:24,052] [WARNING] [comm.py:163:init_deepspeed_backend] HCCL backend in DeepSpeed not yet implemented
(HPUDeepSpeedWorker pid=17869) [2024-03-30 05:05:24,052] [INFO] [comm.py:637:init_distributed] cdb=None
[INFO 2024-03-30 05:05:24,147] client.py: 577  Deployment 'PredictorDeployment:bJbfhC' is ready. component=serve deployment=PredictorDeployment
[INFO 2024-03-30 05:05:24,147] client.py: 577  Deployment 'Router:HiWbWq' is ready at `http://0.0.0.0:8000/`. component=serve deployment=Router
2024-03-30 05:05:24,151 INFO router.py:959 -- Using router <class 'ray.serve._private.router.PowerOfTwoChoicesReplicaScheduler'>.
2024-03-30 05:05:24,157 INFO router.py:496 -- Got updated replicas for deployment 'Router' in application 'router': {'router#Router#QfcfYo'}.
Deployment is ready at `http://0.0.0.0:8000/`.
Service is deployed successfully.(ServeReplica:router:PredictorDeployment pid=17618) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::HPUDeepSpeedWorker.load_model_and_tokenizer() (pid=17874, ip=172.17.0.2, actor_id=2622917f05a3b4a94a2b086a01000000, repr=<llm_on_ray.inference.hpu_predictor.HPUDeepSpeedWorker object at 0x7fbe57de8700>)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 232, in load_model_and_tokenizer
(ServeReplica:router:PredictorDeployment pid=17618)     self.load_model(model_desc, model_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/llm_on_ray/inference/hpu_predictor.py", line 275, in load_model
(ServeReplica:router:PredictorDeployment pid=17618)     engine = deepspeed.init_inference(model, **ds_inference_kwargs)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 346, in init_inference
(ServeReplica:router:PredictorDeployment pid=17618)     engine = InferenceEngine(model, config=ds_inference_config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
(ServeReplica:router:PredictorDeployment pid=17618)     self._apply_injection_policy(config, client_module)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
(ServeReplica:router:PredictorDeployment pid=17618)     replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
(ServeReplica:router:PredictorDeployment pid=17618)   File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 340, in replace_transformer_layer
(ServeReplica:router:PredictorDeployment pid=17618)     replaced_module = set_lm_head(replaced_module)
(ServeReplica:router:PredictorDeployment pid=17618) UnboundLocalError: local variable 'replaced_module' referenced before assignment

**Comment by carsonwang** [comment]
Issue was resolved offline after configurating correct path.
