### ISSUE TITLE
Install vLLM from upstream as CPU backend was merged.

### ISSUE THREAD

**Issue by xwu99** [intel/llm-on-ray#172]
https://github.com/vllm-project/vllm/pull/3634

**Comment by carsonwang** [comment]
@xwu99 , except for the install script, is there anything else need to be updated? If not, can we update it as earliest?

**Comment by xwu99** [comment]
> @xwu99 , except for the install script, is there anything else need to be updated? If not, can we update it as earliest?

sure, I will take it.
