### ISSUE TITLE
ModuleNotFoundError: No module named 'llm_on_ray.inference'

### ISSUE THREAD

**Issue by jackNhat** [intel/llm-on-ray#174]
Hi, i have installed the server with docker bigdl version according to the instructions. 
`docker build -t ray_llm:bigdl -f dev\docker\Dockerfile.bigdl-cpu .`
The installation completed and I didn't get any errors. However when I run the command, 
`llm_on_ray-serve --config_file bigdl/mistral-7b-v0.1-bigdl.yaml`
I get the error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/llm_on_ray-serve", line 5, in <module>
    from llm_on_ray.inference.serve import main
ModuleNotFoundError: No module named 'llm_on_ray.inference'
```
How to fix it, thank you

**Comment by carsonwang** [comment]
Thanks for reporting the issue! @KepingYan can you please help take a look at this one?

**Comment by KepingYan** [comment]
Hi @jackNhat, When building the Dockerfile, `pip install -e` is used to install packages. There is actually no code in the container. Please mount it when start a container like `docker run -it -v $PWD/:/root/llm-on-ray/ ray_llm:bigdl /bin/bash`.

**Comment by jackNhat** [comment]
So easy, it worked. Many thanks
