### ISSUE TITLE
Finetune on Ray cluster with trial task failed

### ISSUE THREAD

**Issue by iodone** [intel/llm-on-ray#251]
When performing `llm_on_ray-finetune --config_file llm_on_ray/finetune/finetune.yaml` to finetune, the following error occurs: 
```
View detailed results here: /home/work/ray_results/TorchTrainer_2024-06-12_19-08-39
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-06-12_17-52-13_804657_66702/artifacts/2024-06-12_19-08-39/TorchTrainer_2024-06-12_19-08-39/driver_artifacts`
2024-06-12 19:12:22,924	ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_1f1a0_00000
Traceback (most recent call last):
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/worker.py", line 863, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::_Inner.__init__() (pid=118836, ip=10.142.64.53, actor_id=9b4cd2f443263634b3cdcba101000000, repr=TorchTrainer)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 158, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 119, in setup
    setup_kwargs[k] = parameter_registry.get(prefix + k)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/registry.py", line 300, in get
    return ray.get(self.references[k])
ray.exceptions.ReferenceCountingAssertionError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff0100000001e1f505. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object has already been deleted by the reference counting protocol. This should not happen.

Training errored after 0 iterations at 2024-06-12 19:12:22. Total running time: 3min 43s
Error file: /tmp/ray/session_2024-06-12_17-52-13_804657_66702/artifacts/2024-06-12_19-08-39/TorchTrainer_2024-06-12_19-08-39/driver_artifacts/TorchTrainer_1f1a0_00000_0_2024-06-12_19-08-39/error.txt
2024-06-12 19:12:22,931	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/home/work/ray_results/TorchTrainer_2024-06-12_19-08-39' in 0.0038s.

2024-06-12 19:12:22,931	ERROR tune.py:1037 -- Trials did not complete: [TorchTrainer_1f1a0_00000]
2024-06-12 19:12:22,934	WARNING experiment_analysis.py:180 -- Failed to fetch metrics for 1 trial(s):
- TorchTrainer_1f1a0_00000: FileNotFoundError('Could not fetch metrics for TorchTrainer_1f1a0_00000: both result.json and progress.csv were not found at /home/work/ray_results/TorchTrainer_2024-06-12_19-08-39/TorchTrainer_1f1a0_00000_0_2024-06-12_19-08-39')
(TrainTrainable pid=118836, ip=10.142.64.53) Local object store memory usage:
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::_Inner.__init__() (pid=118836, ip=10.142.64.53, actor_id=9b4cd2f443263634b3cdcba101000000, repr=TorchTrainer)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 158, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 119, in setup
    setup_kwargs[k] = parameter_registry.get(prefix + k)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/registry.py", line 300, in get
    return ray.get(self.references[k])
ray.exceptions.ReferenceCountingAssertionError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff0100000001e1f505. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object has already been deleted by the reference counting protocol. This should not happen.(TrainTrainable pid=118836, ip=10.142.64.53)


The above exception was the direct cause of the following exception:

(TrainTrainable pid=118836, ip=10.142.64.53) (global lru) capacity: 38542350336
Traceback (most recent call last):
(TrainTrainable pid=118836, ip=10.142.64.53) (global lru) used: 0%
  File "/home/work/app/miniconda/envs/llm-on-ray/bin/llm_on_ray-finetune", line 8, in <module>
(TrainTrainable pid=118836, ip=10.142.64.53) (global lru) num objects: 0
(TrainTrainable pid=118836, ip=10.142.64.53) (global lru) num evictions: 0
(TrainTrainable pid=118836, ip=10.142.64.53) (global lru) bytes evicted: 0
    sys.exit(main())
(TrainTrainable pid=118836, ip=10.142.64.53)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/llm_on_ray/finetune/finetune.py", line 494, in main
(TrainTrainable pid=118836, ip=10.142.64.53) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::_Inner.__init__() (pid=118836, ip=10.142.64.53, actor_id=9b4cd2f443263634b3cdcba101000000, repr=TorchTrainer)
(TrainTrainable pid=118836, ip=10.142.64.53)   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 158, in __init__
(TrainTrainable pid=118836, ip=10.142.64.53)     self.setup(copy.deepcopy(self.config))
(TrainTrainable pid=118836, ip=10.142.64.53)   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/trainable/util.py", line 119, in setup
(TrainTrainable pid=118836, ip=10.142.64.53)     setup_kwargs[k] = parameter_registry.get(prefix + k)
(TrainTrainable pid=118836, ip=10.142.64.53)   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/tune/registry.py", line 300, in get
    results = trainer.fit()
(TrainTrainable pid=118836, ip=10.142.64.53)     return ray.get(self.references[k])
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/train/base_trainer.py", line 638, in fit
(TrainTrainable pid=118836, ip=10.142.64.53) ray.exceptions.ReferenceCountingAssertionError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff0100000001e1f505. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.
(TrainTrainable pid=118836, ip=10.142.64.53)
(TrainTrainable pid=118836, ip=10.142.64.53) The object has already been deleted by the reference counting protocol. This should not happen.
    raise TrainingFailedError(
ray.train.base_trainer.TrainingFailedError: The Ray Train run failed. Please inspect the previous error messages for a cause. After fixing the issue (assuming that the error is not caused by your own application logic, but rather an error such as OOM), you can restart the run from scratch or continue this run.
To continue this run, you can use: `trainer = TorchTrainer.restore("/home/work/ray_results/TorchTrainer_2024-06-12_19-08-39")`.
To start a new run that will retry on training failures, set `train.RunConfig(failure_config=train.FailureConfig(max_failures))` in the Trainer's `run_config` with `max_failures > 0`, or `max_failures = -1` for unlimited retries.
```

**Comment by harborn** [comment]
logs show that ray cluster you started not worked well, can you share the status of your ray cluster by executiong:
`ray status`
or maybe you force stop the ray cluster by:
`ray stop --force`
and then just execute:
`llm_on_ray-finetune --config_file llm_on_ray/finetune/finetune.yaml`

**Comment by iodone** [comment]
Thank you for your reply. According to your instructions, the service was restarted, but new problems emerged. 
```
available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
(RayTrainWorker pid=178581) lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
(RayTrainWorker pid=145250, ip=10.142.64.53) 2024-06-18 21:24:50,300 - datasets - INFO - PyTorch version 2.2.0+cpu available.
(RayTrainWorker pid=178581) Warning: Cannot load xpu CCL. CCL doesn't work for XPU device
(RayTrainWorker pid=178581) Setting up process group for: env:// [rank=0, world_size=2]
(RayTrainWorker pid=145250, ip=10.142.64.53) [E socket.cpp:957] [c10d] The client socket has timed out after 1800s while trying to connect to (0.0.0.0, 54703).
(RayTrainWorker pid=178581) 2024-06-18 21:24:50,372 - datasets - INFO - PyTorch version 2.2.0+cpu available.
2024-06-18 21:54:51,456	ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_cfcaf_00000
Traceback (most recent call last):
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/worker.py", line 2613, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
```
The result of executing `ray status`:
```
======== Autoscaler status: 2024-06-19 09:22:06.466467 ========
Node status
---------------------------------------------------------------
Active:
 1 node_c3c54f11b833fbc24442f79ce75e9e647cd33965c4327b10958d0ca7
 1 node_5cd1a43e40db8b19b3b51005f977f6a821d83fd6fbb01791ad4a50dc
 1 node_45a82ca1722b7e1bd1bd77a50219cc3936a43e0f330f584f8225a046
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/72.0 CPU
 0B/240.83GiB memory
 0B/107.20GiB object_store_memory

Demands:
 (no resource demands)
```

**Comment by iodone** [comment]
> Thank you for your reply. According to your instructions, the service was restarted, but new problems emerged.
> 
> ```
> available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
> (RayTrainWorker pid=178581) lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
> (RayTrainWorker pid=145250, ip=10.142.64.53) 2024-06-18 21:24:50,300 - datasets - INFO - PyTorch version 2.2.0+cpu available.
> (RayTrainWorker pid=178581) Warning: Cannot load xpu CCL. CCL doesn't work for XPU device
> (RayTrainWorker pid=178581) Setting up process group for: env:// [rank=0, world_size=2]
> (RayTrainWorker pid=145250, ip=10.142.64.53) [E socket.cpp:957] [c10d] The client socket has timed out after 1800s while trying to connect to (0.0.0.0, 54703).
> (RayTrainWorker pid=178581) 2024-06-18 21:24:50,372 - datasets - INFO - PyTorch version 2.2.0+cpu available.
> 2024-06-18 21:54:51,456	ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_cfcaf_00000
> Traceback (most recent call last):
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
>     result = ray.get(future)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
>     return fn(*args, **kwargs)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/worker.py", line 2613, in get
>     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
> ```
> 
> The result of executing `ray status`:
> 
> ```
> ======== Autoscaler status: 2024-06-19 09:22:06.466467 ========
> Node status
> ---------------------------------------------------------------
> Active:
>  1 node_c3c54f11b833fbc24442f79ce75e9e647cd33965c4327b10958d0ca7
>  1 node_5cd1a43e40db8b19b3b51005f977f6a821d83fd6fbb01791ad4a50dc
>  1 node_45a82ca1722b7e1bd1bd77a50219cc3936a43e0f330f584f8225a046
> Pending:
>  (no pending nodes)
> Recent failures:
>  (no failures)
> 
> Resources
> ---------------------------------------------------------------
> Usage:
>  0.0/72.0 CPU
>  0B/240.83GiB memory
>  0B/107.20GiB object_store_memory
> 
> Demands:
>  (no resource demands)
> ```

The job running tracing in the Ray dashboard:

<img width="1565" alt="image" src="https://github.com/intel/llm-on-ray/assets/5451385/7dc8c9b9-453e-4888-9bd2-f754140f3d41">

**Comment by iodone** [comment]
> Thank you for your reply. According to your instructions, the service was restarted, but new problems emerged.
> 
> ```
> available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
> (RayTrainWorker pid=178581) lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
> (RayTrainWorker pid=145250, ip=10.142.64.53) 2024-06-18 21:24:50,300 - datasets - INFO - PyTorch version 2.2.0+cpu available.
> (RayTrainWorker pid=178581) Warning: Cannot load xpu CCL. CCL doesn't work for XPU device
> (RayTrainWorker pid=178581) Setting up process group for: env:// [rank=0, world_size=2]
> (RayTrainWorker pid=145250, ip=10.142.64.53) [E socket.cpp:957] [c10d] The client socket has timed out after 1800s while trying to connect to (0.0.0.0, 54703).
> (RayTrainWorker pid=178581) 2024-06-18 21:24:50,372 - datasets - INFO - PyTorch version 2.2.0+cpu available.
> 2024-06-18 21:54:51,456	ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_cfcaf_00000
> Traceback (most recent call last):
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
>     result = ray.get(future)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
>     return fn(*args, **kwargs)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>   File "/home/work/app/miniconda/envs/llm-on-ray/lib/python3.9/site-packages/ray/_private/worker.py", line 2613, in get
>     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
> ```
> 
> The result of executing `ray status`:
> 
> ```
> ======== Autoscaler status: 2024-06-19 09:22:06.466467 ========
> Node status
> ---------------------------------------------------------------
> Active:
>  1 node_c3c54f11b833fbc24442f79ce75e9e647cd33965c4327b10958d0ca7
>  1 node_5cd1a43e40db8b19b3b51005f977f6a821d83fd6fbb01791ad4a50dc
>  1 node_45a82ca1722b7e1bd1bd77a50219cc3936a43e0f330f584f8225a046
> Pending:
>  (no pending nodes)
> Recent failures:
>  (no failures)
> 
> Resources
> ---------------------------------------------------------------
> Usage:
>  0.0/72.0 CPU
>  0B/240.83GiB memory
>  0B/107.20GiB object_store_memory
> 
> Demands:
>  (no resource demands)
> ```

The problem has been identified, start the ray master node: 'ray start --head --node-ip-address 0.0.0.0', due to node-ip-address = 0.0.0.0
