### ISSUE TITLE
fix import from inference package

### ISSUE THREAD

**Issue by xwu99** [intel/llm-on-ray#57]
I am not sure why finetune and inference are installed as packages in the conda env. depending on if inference exists in current directory and where the script is running. Either package installed or local package will be used when import, which is confusing:

`from inference.inference_config import InferenceConfig, DEVICE_CPU`

**Comment by carsonwang** [comment]
This was the change introduced by the UI change. @KepingYan can explain this.

**Comment by xwu99** [comment]
> This was the change introduced by the UI change. @KepingYan can explain this.

Talked with @KepingYan, the simplest fix is to use PYTHONPATH which requires minimum changes. Otherwise we can't run the script locally without installing into conda env.
